version: '3'
services:
    web:
      build: .
      ports:
        - 80:9000
      restart: always
    postgres:
      ports:
        - 5432:5432
      image: postgres:9.6
      volumes:
         - ./data/postgres:/var/lib/postgresql/data
         - ./misc/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
