version: '3'
services:
    postgres:
      image: postgres
      environment:
        POSTGRES_PASSWORD: 'mysecretpassword'
        POSTGRES_USER: postgres
      volumes:
         - ./misc/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      ports:
         - "5432:5432"
